### ISSUE TITLE
Can't extract system.img

### ISSUE THREAD

**Issue by congviet** [ehlers/unyaffs#4]
ynyaffs can't extract the system.img in http://maseco.com.vn/site/arirangnew/2014/T10/STV3600/update.zip
how to fix? thanks

**Comment by ehlers** [comment]
The problem is, that your files have header information in the begin of the file, that doesn't conform to the yaffs specification. I will have a closer look and see, if I can handle this in the program.

Meanwhile the only workaround is to cut off this header, in your case it's the first 2 sector with 8560 bytes each (total 17120). If you use unix, it can be done with dd:

```
dd if=system.img of=system2.img bs=8560 skip=2
dd if=userdata.img of=userdata2.img bs=8560 skip=2
```

Afterwards unyaffs can handle system2.img and userdata2.img normally.

**Comment by ehlers** [comment]
Sorry, I'm totally wrong. It's too long ago, since I touched this program.

The images don't have a header, instead the first data sector of the first file comes before it's file header. unyaffs normally can handle this since v0.9.2. So this should work.

The problem is, that the chunk id (a sequence number) of the first data sector should be 1. In the first file it is 0x400, all other files have the correct value of 1. If you patch this bad chunk id to 1, unyaffs works.

On unix/linux you can patch with these commands:
```
echo "00200a: 0100" | xxd -r - system.img
echo "00200a: 0100" | xxd -r - userdata.img
```

So in my view, these images are invalid yaffs2 files. I won't change unyaffs to deal with this special issue.
